FROM pytorch/pytorch:1.5.1-cuda10.1-cudnn7-devel
RUN apt-get update && \
    apt-get install -y wget && \ 
    apt-get install -y vim &&\
    apt-get install -y libboost-all-dev && \
    apt-get install -y sudo && \
    apt-get install -y libglib2.0-0

# For creating data
RUN apt -y update && apt install -y libgl1-mesa-glx

# Some requirements
RUN pip install --upgrade pip \
                setuptools \
                wheel \
                opencv-python 
            
RUN pip install scikit-image \                                                                                             
                scipy         \                                                                                            
                numba          \                                                                                           
                matplotlib      \                                                                                          
                fire            \                                                                                          
                protobuf        \                                                                                          
                opencv-contrib-python \                                                                                     
                pybind11         \                                                                                         
                vtk               \                                                                                        
                joblib             \                                                                                       
                easydict            \                                                                                      
                open3d-python        \                                                                                     
                terminaltables        \                                                                                    
                pytest-runner          \                                                                                   
                addict                  \                                                                                  
                pycocotools              \                                                                                 
                imagecorruptions          \                                                                                
                objgraph                   \                                                                               
                cachetools \
                descartes \
                jupyter \
                matplotlib \
                motmetrics==1.1.3 \
                numpy \
                pandas==0.24 \
                Pillow==6.2.1  \
                pyquaternion==0.9.5 \
                scikit-learn \
                Shapely \
                tqdm \
                pyyaml \
                requests \
                tensorboard_logger \
                einops \
                pudb

RUN pip install ml-collections

RUN export PYTHONPATH=$PYTHONPATH:/workspace
WORKDIR /workspace
ADD ./ ./
ADD train_local.sh /bin/train 
RUN chmod +x /bin/train

CMD ["/bin/bash"]











