datasets:
    ilsvrc2012:
      name: &dataset_name ''
      type: 'ImageFolder'
      root: &root_dir '/path/to/the/imagenet/folder'
      splits:
        train:
          dataset_id: &imagenet_train !join [*dataset_name, '/train']
          params:
            root: !join [*root_dir, '/train']
            transform_params:
              - type: 'RandomResizedCrop'
                params:
                  size: &input_size [224, 224]
              - type: 'RandomHorizontalFlip'
                params:
                  p: 0.5
              - &totensor
                type: 'ToTensor'
                params:
              - &normalize
                type: 'Normalize'
                params:
                  mean: [0.485, 0.456, 0.406]
                  std: [0.229, 0.224, 0.225]
        val:
          dataset_id: &imagenet_val !join [*dataset_name, '/val']
          params:
            root: !join [*root_dir, '/val']
            transform_params:
              - type: 'Resize'
                params:
                  size: 256
              - type: 'CenterCrop'
                params:
                  size: *input_size
              - *totensor
              - *normalize
  
  models:
    teacher_model:
      name: &teacher_model_name 'resnet34'
      params:
        num_classes: 1000
        pretrained: True
      experiment: &teacher_experiment !join ['imagenet', '-', *teacher_model_name]
      ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
    student_model:
      name: &student_model_name 'resnet18'
      params:
        num_classes: 1000
        pretrained: True
      experiment: &student_experiment !join ['imagenet', '-', *student_model_name, '_from_', *teacher_model_name]
      ckpt: !join ['./model/', *student_experiment, '.pt']
  
  train:
    log_freq: 200
    num_epochs: 100
    train_data_loader:
      dataset_id: *imagenet_train
      random_sample: True
      batch_size: 256 #per gpu
      num_workers: 10
      cache_output:
    val_data_loader:
      dataset_id: *imagenet_val
      random_sample: False
      batch_size: 32
      num_workers: 2
    teacher:
      sequential: []
      special:
        type: 'AttnEmbed'
        params:
          embedings:
            key:
              io: 'output'
              path: 'model.layer4'
              in_channels: 512
              out_channels: 512
      forward_hook:
        input: []
        output: ['model.layer4','embed_dict.key']
      wrapper: #'DistributedDataParallel'
      requires_grad: True
      frozen_modules: ['model'] # The ResNet
    student:
      adaptations:
      sequential: []
      special:
        type: 'AttnEmbed'
        params:
          embedings:
            query:
              io: 'output'
              path: 'model.layer4'
              in_channels: 512
              out_channels: 512
            value:
              io: 'output'
              path: 'model.layer4'
              in_channels: 512
              out_channels: 512
      forward_hook:
        input: []
        output: ['model.layer4', 'embed_dict.query', 'embed_dict.value']
      wrapper: 
      requires_grad: True
      frozen_modules: []
    apex:
      requires: False
      opt_level: '01'
    optimizer:
      type: 'AdamW'
      params:
        lr: 0.0016
        #momentum: 0.9
        weight_decay: 0.0005
    scheduler:
      type: 'MultiStepLR'
      params:
        milestones: [30, 60, 90]
        gamma: 0.1
    criterion:
      type: 'GeneralizedCustomLoss'
      org_term:
        criterion:
          type: 'KDLoss'
          params:
            temperature: 1.0
            alpha: 0.5
            beta: 0.5
            reduction: 'batchmean'
        factor: 1.0
      sub_terms:
        cs:
          criterion:
            type: 'MaskedFM'
            params:
              feature_pairs:
                pair1:
                  teacher:
                    io: 'output'
                    path: ['model.layer4', 'embed_dict.key']
                  student:
                    io: 'output'
                    path: ['model.layer4', 'embed_dict.query','embed_dict.value']
                  factor: 1
              heads: 1
          factor: 0.1
  test:
    test_data_loader:
      dataset_id: *imagenet_val
      random_sample: False
      batch_size: 1
      num_workers: 16
  